#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Kenta IDA <fuga@fugafuga.org>
# SPDX-License-Identifier: BSL-1.0
#
# Build the avatar face renderer to a single self-contained HTML file using
# Emscripten (run from a Docker image — no host toolchain needed). The avatar
# C++ animation + VM code is compiled verbatim against a tiny framebuffer
# M5GFX shim (wasm/shim/M5GFX.h); see wasm/avatar_wasm.cpp for the glue.
#
# The default face DSL is compiled to bytecode by the same Node CLI the
# firmware uses (tools/avatar_dsl/cli.mjs), then embedded into the WASM module
# via a generated default_face_avbc.h byte array. The JS DSL compiler
# (lexer/parser/emitter) is concatenated into a single IIFE bundle and inlined
# into the standalone shell so the live preview can edit + recompile DSL in the
# browser without any extra HTTP fetches (SINGLE_FILE friendly).
#
# Usage: wasm/build.sh            # build -> build/avatar_web/avatar.html
#        EMSDK_IMAGE=... wasm/build.sh   # override the emscripten image
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
IMAGE="${EMSDK_IMAGE:-emscripten/emsdk:3.1.74}"
# Standalone preview page (shell UI + canvas). Loaded directly in a browser.
OUT_HTML="build/avatar_web/avatar.html"
# Embeddable module (no shell UI): a single self-contained JS that defines
# AvatarModule() → Promise<Module>. tools/settings.html loads this to render the
# in-page live avatar preview; pages.yml deploys it next to settings.html.
OUT_MODULE="build/avatar_web/avatar_module.js"

mkdir -p "$ROOT/build/avatar_web" "$ROOT/build/emcache"

# --- Compile the default avatar face DSL to bytecode + generate the C header
# that pulls it into the WASM module as a byte array. Same CLI / same .avdsl as
# the firmware build, so both targets stay in lockstep. Paths kept relative to
# $ROOT so they resolve the same way inside the docker container (which mounts
# $ROOT at /src) as on the host.
DSL_OUT_DIR="$ROOT/build/avatar_web"
DSL_OUT_REL="build/avatar_web"
AVBC="$DSL_OUT_DIR/default_face.avbc"
AVBC_H="$DSL_OUT_DIR/default_face_avbc.h"
node "$ROOT/tools/avatar_dsl/cli.mjs" "$ROOT/assets/default_face.avdsl" "$AVBC"

# xxd-equivalent in pure shell so this works in the emscripten container too
# (the docker image likely has neither xxd nor node, hence doing this on the
# host before launching emcc).
python3 - "$AVBC" "$AVBC_H" << 'PY'
import sys, pathlib
data = pathlib.Path(sys.argv[1]).read_bytes()
out = ['// Generated by wasm/build.sh — do not edit.',
       '#pragma once',
       '#include <cstddef>',
       '#include <cstdint>',
       '',
       f'inline constexpr std::size_t kDefaultFaceAvbcLen = {len(data)};',
       'inline constexpr std::uint8_t kDefaultFaceAvbc[] = {']
hex_bytes = ['0x%02x,' % b for b in data]
# wrap at 12 per line for legibility
for i in range(0, len(hex_bytes), 12):
    out.append('    ' + ' '.join(hex_bytes[i:i+12]))
out.append('};')
pathlib.Path(sys.argv[2]).write_text('\n'.join(out) + '\n')
PY

# --- Bundle the JS DSL compiler + inline both it and the default DSL source
# text into shell.html. Same script as the firmware build
# (components/wifi_config_service/CMakeLists.txt) so the standalone preview
# and the on-device settings page share one bundle implementation. emcc's
# --shell-file does its own {{{ SCRIPT }}} / {{{ BODY }}} substitution after,
# so our placeholder swap MUST happen first.
PROCESSED_SHELL="$DSL_OUT_DIR/shell.processed.html"
PROCESSED_SHELL_REL="$DSL_OUT_REL/shell.processed.html"
node "$ROOT/tools/avatar_dsl/inject.mjs" \
    "$ROOT/wasm/shell.html" \
    "$PROCESSED_SHELL" \
    "default=$ROOT/assets/default_face.avdsl" \
    "omega=$ROOT/assets/omega_mouth.avdsl" \
    "aokko=$ROOT/assets/aokko_face.avdsl"

EXPORTS='_avatar_init,_avatar_set_size,_avatar_width,_avatar_height,_avatar_framebuffer,_avatar_set_expression,_avatar_set_mouth,_avatar_set_manual_gaze,_avatar_set_saccade,_avatar_set_blink,_avatar_set_breath,_avatar_set_colors,_avatar_set_eyebrows_visible,_avatar_set_eye_params,_avatar_set_eyebrow_params,_avatar_set_mouth_params,_avatar_set_direct,_avatar_tick,_avatar_load_bytecode,_avatar_reset_bytecode,_malloc,_free'

# Shared compile inputs/flags for both outputs (same C++, same exports). Kept
# on single lines so the values interpolate cleanly into the `bash -c` script
# below (an embedded newline would prematurely terminate the emcc command).
SRCS='wasm/avatar_wasm.cpp components/avatar/animation.cpp components/avatar_vm/decoder.cpp components/avatar_vm/vm.cpp'
INCS='-I wasm/shim -I components/avatar -I components/avatar/include -I components/avatar_vm/include -I components/tl_expected/expected/include -I build/avatar_web'
COMMON="-std=c++20 -O2 $INCS $SRCS -sSINGLE_FILE=1 -sEXPORTED_FUNCTIONS=$EXPORTS -sEXPORTED_RUNTIME_METHODS=ccall,cwrap,HEAPU16,HEAPU8 -sALLOW_MEMORY_GROWTH=1 -sENVIRONMENT=web"

echo "[avatar-wasm] building with $IMAGE -> $OUT_HTML + $OUT_MODULE"
# Both outputs are produced in a single container invocation (one emcc per
# output) to avoid re-pulling the image / re-warming the cache twice. The
# standalone shell carries the DSL editor; the embeddable module skips the
# shell (the host page provides its own UI).
docker run --rm \
  -v "$ROOT:/src" -w /src \
  --user "$(id -u):$(id -g)" \
  -e HOME=/tmp \
  -e EM_CACHE=/src/build/emcache \
  "$IMAGE" \
  bash -c "set -e
    emcc $COMMON --shell-file '$PROCESSED_SHELL_REL' -o '$OUT_HTML'
    emcc $COMMON -sMODULARIZE=1 -sEXPORT_NAME=AvatarModule -o '$OUT_MODULE'"

echo "[avatar-wasm] done: $ROOT/$OUT_HTML"
echo "[avatar-wasm] done: $ROOT/$OUT_MODULE"
